version: '2.3'
services:
  mysql:
    image: mysql:5.7.24
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
  dss:
    image: dss
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 180s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./dss:/home/wso2carbon/wso2-server-volume
    ports:
      - "9443:9443"
      - "9763:9763"
    links:
      - mysql
  aac:
    image: aac
    volumes:
      - ./aac/application-local.yml:/home/aac/aac/src/main/resources/application-local.yml
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:8080/aac/login"]
      interval: 10s
      timeout: 180s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
      api-manager:
        condition: service_healthy
    links:
      - mysql  
